/**
 * Copyright © 2014-2026 PDF Technologies, Inc. All Rights Reserved.
 *
 * THIS SOURCE CODE AND ANY ACCOMPANYING DOCUMENTATION ARE PROTECTED BY INTERNATIONAL COPYRIGHT LAW
 * AND MAY NOT BE RESOLD OR REDISTRIBUTED. USAGE IS BOUND TO THE ComPDFKit LICENSE AGREEMENT.
 * UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS SUBJECT TO CIVIL AND CRIMINAL PENALTIES.
 * This notice may not be removed from this file.
 */

import { Platform } from 'react-native';
import { ComPDFKit } from '@compdfkit_pdf_sdk/react_native';

import type { ExampleItem, ExamplePlatform } from './shared/exampleItem';
import type { ExampleRouteName } from './shared/exampleRoutes';
import { EXAMPLE_ROUTE_TYPES } from './shared/exampleRouteType';

export type ExampleNavigation = {
  navigate: (routeName: ExampleRouteName, params?: Record<string, unknown>) => void;
};

const currentPlatform: ExamplePlatform =
  Platform.OS === 'ios' ? 'ios' : 'android';

export function isExampleSupported(example: ExampleItem) {
  return (
    !example.supportedPlatforms ||
    example.supportedPlatforms.includes(currentPlatform)
  );
}

export function getSupportedExamples(examples: ExampleItem[]) {
  return examples.filter(isExampleSupported);
}

/**
 * Opens a PDF document using the global SDK entry point.
 *
 * `ComPDFKit.openDocument(path, password, configuration)` launches a
 * full-screen reader view. The configuration string is generated by
 * `ComPDFKit.getDefaultConfig({})` which applies persisted user preferences.
 */
async function openDocument(documentPath: string) {
  await ComPDFKit.openDocument(documentPath, '', ComPDFKit.getDefaultConfig({}));
}

/**
 * Opens the native file picker for PDF files.
 *
 * `ComPDFKit.pickFile()` presents the platform file picker filtered
 * to PDF documents and returns the selected file path, or `undefined` if cancelled.
 */
async function pickDocument() {
  const documentPath = await ComPDFKit.pickFile();
  return documentPath ?? null;
}

export async function executeExampleItem(
  example: ExampleItem,
  navigation: ExampleNavigation,
) {
  if (!isExampleSupported(example)) {
    return;
  }

  if (
    example.routeType === EXAMPLE_ROUTE_TYPES.screen &&
    example.routeName
  ) {
    navigation.navigate(example.routeName, example.params);
    return;
  }

  if (
    example.routeType === EXAMPLE_ROUTE_TYPES.modalCallback &&
    example.modalCallback
  ) {
    await example.modalCallback({
      navigate: navigation.navigate,
      openDocument,
      pickDocument,
    });
  }
}